module.exports = {
  apps: [
    {
      name: 'anxun-caoliao-webhook',
      script: './server/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      watch: false,
      env: {
        NODE_ENV: 'production',
        WEBHOOK_PORT: process.env.WEBHOOK_PORT || '8787',
        DB_HOST: process.env.DB_HOST || '',
        DB_PORT: process.env.DB_PORT || '3306',
        DB_NAME: process.env.DB_NAME || '',
        DB_USER: process.env.DB_USER || '',
        DB_PASSWORD: process.env.DB_PASSWORD || '',
        DB_SSL: process.env.DB_SSL || 'false',
        DB_TIME_ZONE: process.env.DB_TIME_ZONE || '+08:00',
        DB_POOL_SIZE: process.env.DB_POOL_SIZE || '5',
        DB_CONNECT_TIMEOUT_MS: process.env.DB_CONNECT_TIMEOUT_MS || '2500',
        BUSINESS_TIME_ZONE: process.env.BUSINESS_TIME_ZONE || 'Asia/Shanghai',
        PINGXIANG_DATA_SOURCE: process.env.PINGXIANG_DATA_SOURCE || 'demo',
        PINGXIANG_SOURCE_ENVIRONMENT: process.env.PINGXIANG_SOURCE_ENVIRONMENT || 'real',
        MYSQL_WRITE_ENABLED: process.env.MYSQL_WRITE_ENABLED || 'false',
        CAOLIAO_CONNECTOR_KEY: process.env.CAOLIAO_CONNECTOR_KEY || 'caoliao-pingxiang-test',
        CAOLIAO_SOURCE_ENVIRONMENT: process.env.CAOLIAO_SOURCE_ENVIRONMENT || 'test',
        WEBHOOK_AUTH_REQUIRED: process.env.WEBHOOK_AUTH_REQUIRED || 'false',
        WEBHOOK_ALLOW_QUERY_TOKEN: process.env.WEBHOOK_ALLOW_QUERY_TOKEN || 'false',
        CAOLIAO_WEBHOOK_SECRET: process.env.CAOLIAO_WEBHOOK_SECRET || '',
        WEBHOOK_LOG_MAX_BYTES: process.env.WEBHOOK_LOG_MAX_BYTES || '20971520',
        WEBHOOK_LOG_RETAINED_FILES: process.env.WEBHOOK_LOG_RETAINED_FILES || '5',
        INTERNAL_DATA_API_KEY: process.env.INTERNAL_DATA_API_KEY || '',
        INTERNAL_DATA_ALLOW_LOOPBACK: process.env.INTERNAL_DATA_ALLOW_LOOPBACK || 'false',
      },
    },
  ],
}
