module.exports = {
  apps: [
    {
      name: 'anxun-caoliao-webhook',
      script: './server/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      watch: false,
      env: {
        NODE_ENV: 'production',
        WEBHOOK_PORT: process.env.WEBHOOK_PORT || '8787',
        DB_HOST: process.env.DB_HOST || '',
        DB_PORT: process.env.DB_PORT || '3306',
        DB_NAME: process.env.DB_NAME || '',
        DB_USER: process.env.DB_USER || '',
        DB_PASSWORD: process.env.DB_PASSWORD || '',
        DB_SSL: process.env.DB_SSL || 'false',
        DB_TIME_ZONE: process.env.DB_TIME_ZONE || '+08:00',
        DB_POOL_SIZE: process.env.DB_POOL_SIZE || '5',
        DB_CONNECT_TIMEOUT_MS: process.env.DB_CONNECT_TIMEOUT_MS || '2500',
        BUSINESS_TIME_ZONE: process.env.BUSINESS_TIME_ZONE || 'Asia/Shanghai',
        PINGXIANG_DATA_SOURCE: process.env.PINGXIANG_DATA_SOURCE || 'demo',
        PINGXIANG_SOURCE_ENVIRONMENT: process.env.PINGXIANG_SOURCE_ENVIRONMENT || 'real',
        MYSQL_WRITE_ENABLED: process.env.MYSQL_WRITE_ENABLED || 'false',
        CAOLIAO_CONNECTOR_KEY: process.env.CAOLIAO_CONNECTOR_KEY || 'caoliao-pingxiang-test',
        CAOLIAO_SOURCE_ENVIRONMENT: process.env.CAOLIAO_SOURCE_ENVIRONMENT || 'test',
        WEBHOOK_AUTH_REQUIRED: process.env.WEBHOOK_AUTH_REQUIRED || 'false',
        WEBHOOK_ALLOW_QUERY_TOKEN: process.env.WEBHOOK_ALLOW_QUERY_TOKEN || 'false',
        CAOLIAO_WEBHOOK_SECRET: process.env.CAOLIAO_WEBHOOK_SECRET || '',
        WEBHOOK_LOG_MAX_BYTES: process.env.WEBHOOK_LOG_MAX_BYTES || '20971520',
        WEBHOOK_LOG_RETAINED_FILES: process.env.WEBHOOK_LOG_RETAINED_FILES || '5',
        INTERNAL_DATA_API_KEY: process.env.INTERNAL_DATA_API_KEY || '',
        INTERNAL_DATA_ALLOW_LOOPBACK: process.env.INTERNAL_DATA_ALLOW_LOOPBACK || 'false',
        AUTH_COOKIE_NAME: process.env.AUTH_COOKIE_NAME || 'anxun_session',
        AUTH_CSRF_COOKIE_NAME: process.env.AUTH_CSRF_COOKIE_NAME || 'anxun_csrf',
        AUTH_COOKIE_SECURE: process.env.AUTH_COOKIE_SECURE || 'true',
        AUTH_TRUSTED_ORIGINS: process.env.AUTH_TRUSTED_ORIGINS || 'https://axsztech.cn,https://www.axsztech.cn',
        AUTH_SESSION_IDLE_MINUTES: process.env.AUTH_SESSION_IDLE_MINUTES || '120',
        AUTH_SESSION_MAX_HOURS: process.env.AUTH_SESSION_MAX_HOURS || '12',
        AUTH_BCRYPT_ROUNDS: process.env.AUTH_BCRYPT_ROUNDS || '12',
        AUTH_LOGIN_MAX_ATTEMPTS: process.env.AUTH_LOGIN_MAX_ATTEMPTS || '5',
        AUTH_LOGIN_LOCK_MINUTES: process.env.AUTH_LOGIN_LOCK_MINUTES || '15',
        AUTH_LOGIN_RATE_LIMIT: process.env.AUTH_LOGIN_RATE_LIMIT || '10',
        AUTH_API_RATE_LIMIT_PER_MINUTE: process.env.AUTH_API_RATE_LIMIT_PER_MINUTE || '600',
        WEBHOOK_RATE_LIMIT_PER_MINUTE: process.env.WEBHOOK_RATE_LIMIT_PER_MINUTE || '300',
        REPORT_PDF_FONT_PATH: process.env.REPORT_PDF_FONT_PATH || '',
        P3_AI_ASSISTANT_ENABLED: process.env.P3_AI_ASSISTANT_ENABLED || 'false',
        P3_AI_ADMIN_ONLY: process.env.P3_AI_ADMIN_ONLY || 'true',
        P3_AI_SOURCE_ENVIRONMENT: process.env.P3_AI_SOURCE_ENVIRONMENT || 'test',
        P3_AI_DAILY_LIMIT: process.env.P3_AI_DAILY_LIMIT || '20',
        P3_AI_RATE_LIMIT_PER_MINUTE: process.env.P3_AI_RATE_LIMIT_PER_MINUTE || '20',
        P3_AI_TIMEOUT_MS: process.env.P3_AI_TIMEOUT_MS || '12000',
        P3_AI_MAX_OUTPUT_TOKENS: process.env.P3_AI_MAX_OUTPUT_TOKENS || '400',
        DEEPSEEK_MODEL: process.env.DEEPSEEK_MODEL || 'deepseek-v4-flash',
        DEEPSEEK_API_KEY: process.env.DEEPSEEK_API_KEY || '',
      },
    },
  ],
}
